version: "3.8"

services:
  audacity:
    image: lscr.io/linuxserver/audacity:latest
    container_name: audacity
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Makassar
      - SELKIES_AUDIO=false
      - SELKIES_MICROPHONE=false
      - SELKIES_GAMEPAD=false
    volumes:
      - ./config:/config
      - ./audio:/audio
    networks:
      - audacity_net
    expose:
      - "3001"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    networks:
      - audacity_net
    command: >
      tunnel --no-autoupdate run --token eyJhIjoiYjY0ZGIyODBlM2MzYTVjNTIzMDA0M2IwNzk0MDI3NjciLCJ0IjoiZjhmNmFjYjQtMThlMi00NzZjLTlkMzYtOGM0ZGUxMWQ2NDRkIiwicyI6Ik5HTTNaREV5TmpJdE5XTXhaQzAwWWpVeExUazFabVF0WkRFd016ZGhZMlZqTkRoaCJ9

networks:
  audacity_net:
    driver: bridge
